import {readFile,writeFile,rename,mkdir} from 'node:fs/promises';
import path from 'node:path';
import {createHash} from 'node:crypto';
import {applyAcceptance} from './lib/notebook-contract.mjs';
const [, , dirArg, reviewArg] = process.argv;
if(!dirArg || !reviewArg) throw Error('Usage: node scripts/notebooklm-accept.mjs <case-dir> <review-json-relative-to-case>');
const dir=path.resolve(dirArg);
const local = p => {const f=path.resolve(dir,p);if(!f.startsWith(dir+path.sep))throw Error('Artifact outside case');return f;};
const readJson=async p=>JSON.parse(await readFile(p,'utf8'));
const state=await readJson(local('state.json'));
const review=await readJson(local(reviewArg));
const audit=await readJson(local(review.auditPath));
review.receipt=await readJson(local(review.sourceReceipt));
const hashes={};for(const name of ['effectiveAnswer','auditPath','sourceReceipt'])hashes[name]=createHash('sha256').update(await readFile(local(review[name]))).digest('hex');
const updated=applyAcceptance(state,review,audit,hashes);
await mkdir(local('reviews'),{recursive:true});
await writeFile(local(`reviews/${review.stepId}-${review.version}-accepted.json`),JSON.stringify({review,hashes,at:new Date().toISOString()},null,2),{flag:'wx'});
await writeFile(local('state.json.accept.tmp'),JSON.stringify(updated,null,2));await rename(local('state.json.accept.tmp'),local('state.json'));
console.log(JSON.stringify({accepted:review.stepId,version:review.version,next:updated.notebook.currentQuestion,phase:updated.phase}));
